require("impatient")
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.editorconfig"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsign"
require "user.nvim-tree"
require "user.lualine"
require "user.blankline"
require "user.colorizer"
require "user.document-color"
